-- Kreiranje Product i Worker tabela za Supabase (Postgres)

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    naziv text not null
);

create table if not exists public.workers (
    id bigint generated by default as identity primary key,
    ime text not null,
    prezime text not null,
    product_id bigint not null,
    constraint fk_workers_product
        foreign key (product_id)
        references public.products (id)
        on delete cascade
);

create index if not exists idx_workers_product_id
    on public.workers(product_id);

-- Primer podataka
insert into public.products (naziv)
values
    ('Mašina A'),
    ('Mašina B')
on conflict do nothing;

insert into public.workers (ime, prezime, product_id)
values
    ('Marko', 'Marković', 1),
    ('Nikola', 'Nikolić', 1),
    ('Jovan', 'Jovanović', 2)
on conflict do nothing;
